package com.utm2maps.ui

import com.utm2maps.data.InterfaceLanguage

data class UiStrings(
    val appName: String,
    val appTagline: String,
    val logoText: String,
    val chooseImage: String,
    val takeImage: String,
    val settings: String,
    val result: String,
    val copyLink: String,
    val linkCopied: String,
    val openInGoogleMaps: String,
    val shareLink: String,
    val shareChooserTitle: String,
    val scanAnotherImage: String,
    val noValidCoordinateFound: String,
    val manualTextTitle: String,
    val manualTextPlaceholder: String,
    val extractCoordinateFromText: String,
    val noValidCoordinateInText: String,
    val copyRecognizedText: String,
    val recognizedTextCopied: String,
    val extractCoordinateFromThisText: String,
    val pasteTextManually: String,
    val recognizedTextFromImage: String,
    val noTextRecognized: String,
    val tapLineToCopyAndExtract: String,
    val lineCopied: String,
    val noCoordinateInSelectedLine: String,
    val selectedTextForExtraction: String,
    val copySelectedText: String,
    val extractCoordinateFromSelectedText: String,
    val copyAllText: String,
    val selectedTextCopied: String,
    val lastResult: String,
    val noScanYet: String,
    val openResult: String,
    val scanningImage: String,
    val ocrText: String,
    val selectedUtm: String,
    val chooseCoordinate: String,
    val rawInput: String,
    val easting: String,
    val fullNorthing: String,
    val zone: String,
    val latitude: String,
    val longitude: String,
    val googleMapsLink: String,
    val back: String,
    val save: String,
    val cancel: String,
    val utmSettings: String,
    val appSettings: String,
    val about: String,
    val zoneNumber: String,
    val latitudeBand: String,
    val hemisphere: String,
    val northingPrefix: String,
    val autoOpenGoogleMaps: String,
    val copyLinkAutomatically: String,
    val interfaceLanguage: String,
    val hebrew: String,
    val english: String,
    val north: String,
    val south: String,
    val conversionHint: String,
    val createdBy: String,
    val createdByEmail: String,
    val createdByFull: String,
    val cameraPermissionDenied: String,
    val ocrFailed: String
)

fun stringsFor(language: InterfaceLanguage): UiStrings = when (language) {
    InterfaceLanguage.HEBREW -> hebrewStrings
    InterfaceLanguage.ENGLISH -> englishStrings
}

private val hebrewStrings = UiStrings(
    appName = "UTM2Maps",
    appTagline = "המרת קואורדינטות UTM לקישור Google Maps",
    logoText = "UTM",
    chooseImage = "בחירת תמונה",
    takeImage = "צילום תמונה",
    settings = "הגדרות",
    result = "תוצאה",
    copyLink = "העתקת קישור",
    linkCopied = "הקישור הועתק",
    openInGoogleMaps = "פתיחה בגוגל מפות",
    shareLink = "שיתוף קישור",
    shareChooserTitle = "שיתוף קישור Google Maps",
    scanAnotherImage = "סריקת תמונה נוספת",
    noValidCoordinateFound = "לא נמצאה קואורדינטת UTM תקינה בתמונה",
    manualTextTitle = "הדבקת טקסט ידנית",
    manualTextPlaceholder = "הדבק או הקלד טקסט עם נ״צ UTM, למשל: נצ הנחתה 625854/439328",
    extractCoordinateFromText = "חילוץ נ״צ מהטקסט",
    noValidCoordinateInText = "לא נמצאה קואורדינטת UTM תקינה בטקסט",
    copyRecognizedText = "העתקת הטקסט שזוהה",
    recognizedTextCopied = "הטקסט שזוהה הועתק",
    extractCoordinateFromThisText = "חילוץ נ״צ מהטקסט הזה",
    pasteTextManually = "הדבקת טקסט ידנית",
    recognizedTextFromImage = "טקסט שזוהה בתמונה",
    noTextRecognized = "לא זוהה טקסט בתמונה",
    tapLineToCopyAndExtract = "לחץ על שורה כדי להעתיק ולחלץ נ״צ",
    lineCopied = "השורה הועתקה",
    noCoordinateInSelectedLine = "לא נמצאה קואורדינטת UTM בשורה שנבחרה",
    selectedTextForExtraction = "טקסט נבחר לחילוץ",
    copySelectedText = "העתקת הטקסט הנבחר",
    extractCoordinateFromSelectedText = "חילוץ נ״צ מהטקסט הנבחר",
    copyAllText = "העתקת כל הטקסט",
    selectedTextCopied = "הטקסט הנבחר הועתק",
    lastResult = "תוצאה אחרונה",
    noScanYet = "עדיין לא בוצעה סריקה",
    openResult = "פתיחת התוצאה",
    scanningImage = "סורק תמונה ומזהה טקסט...",
    ocrText = "טקסט שזוהה",
    selectedUtm = "קואורדינטה שנבחרה",
    chooseCoordinate = "בחירת קואורדינטה",
    rawInput = "קלט מקורי",
    easting = "מזרח / Easting",
    fullNorthing = "צפון מלא / Full Northing",
    zone = "אזור",
    latitude = "קו רוחב",
    longitude = "קו אורך",
    googleMapsLink = "קישור Google Maps",
    back = "חזרה",
    save = "שמירה",
    cancel = "ביטול",
    utmSettings = "הגדרות UTM",
    appSettings = "הגדרות אפליקציה",
    about = "אודות",
    zoneNumber = "מספר אזור UTM",
    latitudeBand = "רצועת רוחב",
    hemisphere = "המיספרה",
    northingPrefix = "קידומת Northing",
    autoOpenGoogleMaps = "פתיחה אוטומטית בגוגל מפות",
    copyLinkAutomatically = "העתקת קישור אוטומטית",
    interfaceLanguage = "שפת ממשק / Interface Language",
    hebrew = "עברית",
    english = "English",
    north = "צפון",
    south = "דרום",
    conversionHint = "רצועת הרוחב נשמרת להקשר. ההמרה בפועל משתמשת במספר האזור ובהמיספרה.",
    createdBy = "Created by",
    createdByEmail = "yinoncode@gmail.com",
    createdByFull = "Created by yinoncode@gmail.com",
    cameraPermissionDenied = "הרשאת מצלמה נדחתה",
    ocrFailed = "זיהוי הטקסט נכשל"
)

private val englishStrings = UiStrings(
    appName = "UTM2Maps",
    appTagline = "Convert UTM coordinates to a Google Maps link",
    logoText = "UTM",
    chooseImage = "Choose Image",
    takeImage = "Take Image",
    settings = "Settings",
    result = "Result",
    copyLink = "Copy Link",
    linkCopied = "Link copied",
    openInGoogleMaps = "Open in Google Maps",
    shareLink = "Share Link",
    shareChooserTitle = "Share Google Maps link",
    scanAnotherImage = "Scan Another Image",
    noValidCoordinateFound = "No valid UTM coordinate was found in the image",
    manualTextTitle = "Paste text manually",
    manualTextPlaceholder = "Paste or type text with a UTM coordinate, e.g. UTM 625854/439328",
    extractCoordinateFromText = "Extract coordinate from text",
    noValidCoordinateInText = "No valid UTM coordinate was found in the text",
    copyRecognizedText = "Copy recognized text",
    recognizedTextCopied = "Recognized text copied",
    extractCoordinateFromThisText = "Extract coordinate from this text",
    pasteTextManually = "Paste text manually",
    recognizedTextFromImage = "Recognized text from image",
    noTextRecognized = "No text was recognized in the image",
    tapLineToCopyAndExtract = "Tap a line to copy and extract coordinates",
    lineCopied = "Line copied",
    noCoordinateInSelectedLine = "No UTM coordinate was found in the selected line",
    selectedTextForExtraction = "Selected text for extraction",
    copySelectedText = "Copy selected text",
    extractCoordinateFromSelectedText = "Extract coordinate from selected text",
    copyAllText = "Copy all text",
    selectedTextCopied = "Selected text copied",
    lastResult = "Last Result",
    noScanYet = "No scan yet",
    openResult = "Open Result",
    scanningImage = "Scanning image and recognizing text...",
    ocrText = "OCR text",
    selectedUtm = "Selected UTM",
    chooseCoordinate = "Choose Coordinate",
    rawInput = "Raw input",
    easting = "Easting",
    fullNorthing = "Full Northing",
    zone = "Zone",
    latitude = "Latitude",
    longitude = "Longitude",
    googleMapsLink = "Google Maps link",
    back = "Back",
    save = "Save",
    cancel = "Cancel",
    utmSettings = "UTM Settings",
    appSettings = "App Settings",
    about = "About",
    zoneNumber = "UTM Zone Number",
    latitudeBand = "Latitude Band",
    hemisphere = "Hemisphere",
    northingPrefix = "Northing Prefix",
    autoOpenGoogleMaps = "Auto open Google Maps",
    copyLinkAutomatically = "Copy link automatically",
    interfaceLanguage = "Interface Language / שפת ממשק",
    hebrew = "Hebrew",
    english = "English",
    north = "North",
    south = "South",
    conversionHint = "Latitude Band is saved for context. Conversion uses Zone Number and Hemisphere.",
    createdBy = "Created by",
    createdByEmail = "yinoncode@gmail.com",
    createdByFull = "Created by yinoncode@gmail.com",
    cameraPermissionDenied = "Camera permission denied",
    ocrFailed = "OCR failed"
)
